### ISSUE TITLE
Place not fitting the window

### ISSUE THREAD

**Issue by MarreTeint** [stheren/SmartFish#4]
The color picker and the waiting time between two pixels are cropped by the window
![image](https://user-images.githubusercontent.com/96467585/191702425-7855c01b-c886-49cb-89e3-ea50ec249f1c.png)
*Je suis Boogie*

**Comment by maximefromont** [comment]
Hi @MarreTeint !

Are you still experiencing this issue ?

**Comment by MarreTeint** [comment]
yes, might be caused by the scalling of the screen

**Comment by stheren** [comment]
It wil be corrected in future release :)
